sonar.projectKey=307-group_csc307-team-project
sonar.organization=307-group

sonar.projectName=NoteApp
sonar.projectVersion=1.0

sonar.sources=packages/react-frontend/src,packages/express-backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/package-lock.json

#sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=packages/react-frontend/coverage/lcov.info