name: Deploy to Azure

on:
  push:
    branches:
      - main
      - new-frontend-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm install --workspaces=false
          npm run -w express-backend build --if-present
        working-directory: packages/express-backend

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: packages/express-backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Markr"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: packages/express-backend/release.zip
