name: Cypress Tests

on:
  push:
    branches: [main, cypress-testing]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/react-frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: 'packages/react-frontend/package-lock.json'


      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/react-frontend
          start: npm run dev
          wait-on: http://localhost:5173
          browser: chrome