name: SonarQube Cloud

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]


jobs:
  sonarqube:
    name: SonarQube Cloud Scan
    runs-on: ubuntu-latest

    steps: 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run frontend Cypress tests with coverage
        run: |
          npm run -w react-frontend dev &
          npx wait-on http://localhost:5173
          npx cypress run --project packages/react-frontend

      - name: Check coverage file
        run: |
          ls -la packages/react-frontend/coverage
          test -f packages/react-frontend/coverage/lcov.info

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.scanner.skipJreProvisioning=true
